### ISSUE TITLE
error on data-formatter, to lower function

### ISSUE THREAD

**Issue by MelvinDunn** [ClimbsRocks/data-formatter#77]
Trying this out, and I'm getting the following error:

```
message from Python: Warning, we have received a value in the first row that is not valid:
message from Python: “output category”
message from Python: Please remember that the first row must contain information describing that column of data
message from Python: Acceptable values are: "ID", "Output Category", "Output Multi-Category", "Output Regression", "Continuous", "Categorical", "Date", "IGNORE", "Validation Split", and "NLP", though they are not case sensitive.
```

I'm thinking it's a because it's lowering the values and the strings aren't matching.

**Comment by ClimbsRocks** [comment]
Hmm, that shouldn't be throwing an error. Thanks for filling!

Could you try uninstalling and reinstalling data-formatter?

`npm uninstall data-formatter`
`npm install data-formatter`

**Comment by MelvinDunn** [comment]
No problem man. Still getting the same error. I'm running on Mac btw.

$ npm uninstall data-formatter
unbuild data-formatter@1.7.3

$ npm install data-formatter
data-formatter@1.7.3 node_modules/data-formatter

```
message from Python: ‘output category’
message from Python: Please remember that the first row must contain information describing that column of data
message from Python: Acceptable values are: "ID", "Output Category", "Output Multi-Category", "Output Regression", "Continuous", "Categorical", "Date", "IGNORE", "Validation Split", and "NLP", though they are not case sensitive.
message from Python: 
message from Python: The column index of this unexpected value is:
message from Python: 0
message from Python: The entire row that we received is:
message from Python: ['\xe2\x80\x98output category\xe2\x80\x99', ' \xe2\x80\x9ccontinuous\xe2\x80\x9d', ' \xe2\x80\x9ccontinuous\xe2\x80\x9d', ' \xe2\x80\x9ccontinuous\xe2\x80\x9d', ' \xe2\x80\x9ccontinuous\xe2\x80\x9d', ' \xe2\x80\x9ccontinuous\xe2\x80\x9d', ' \xe2\x80\x9ccontinuous\xe2\x80\x9d', ' \xe2\x80\x9ccontinuous\xe2\x80\x9d', ' \xe2\x80\x9ccontinuous\xe2\x80\x9d', ' \xe2\x80\x9ccontinuous\xe2\x80\x9d', ' \xe2\x80\x9ccontinuous\xe2\x80\x9d', ' \xe2\x80\x9ccontinuous\xe2\x80\x9d', ' \xe2\x80\x9ccontinuous\xe2\x80\x9d', ' \xe2\x80\x9ccontinuous\xe2\x80\x9d', ' \xe2\x80\x9ccontinuous\xe2\x80\x9d', ' \xe2\x80\x9ccontinuous\xe2\x80\x9d', ' \xe2\x80\x9ccontinuous\xe2\x80\x9d', ' \xe2\x80\x9ccontinuous\xe2\x80\x9d', ' \xe2\x80\x9ccontinuous\xe2\x80\x9d', ' \xe2\x80\x9ccontinuous\xe2\x80\x9d', ' \xe2\x80\x9ccontinuous\xe2\x80\x9d', ' \xe2\x80\x9ccontinuous\xe2\x80\x9d']
```

**Comment by ClimbsRocks** [comment]
Yeah, that's almost certainly a bug then. I'll investigate once I'm back at
my computer. Thanks for reporting this!

**Comment by ClimbsRocks** [comment]
haha, alright, i think i found it. i tried to replicate on a clean install on my computer, and everything worked. so i took another look at the error messages you nicely provided above. 

if you look carefully, the quotes around the unexpected value (“output category”, and ‘output category’) are different than the standard quotes. 

this is a really annoying problem i've run into before because it's generally not you deciding to go off the rails and use a different type of quote- generally it's some program you're using that chooses to do character encoding in a different way. 

try removing the quotes from that row entirely, and let me know if that works!

**Comment by ClimbsRocks** [comment]
and thanks again for filing the issue and including the full error log!

**Comment by MelvinDunn** [comment]
​
 numerai_tournament_data.csv
https://drive.google.com/file/d/0BxuYVk1RXz_LVHdZSjUzR3h1bjA/view?usp=drive_web
​​
 train_machinejs.csv
https://drive.google.com/file/d/0BxuYVk1RXz_LdVVzbXZoNWtRODA/view?usp=drive_web
​
Hey Preston,

Removing the quotes, unfortunately, did not work.

The files I'm using are attached. Could you help me out using the files?

The output is below:

message from Python:

---

message from Python:

message from Python: Warning, we have received a value in the first row
that is not valid:

message from Python:  continuous

message from Python: Please remember that the first row must contain
information describing that column of data

message from Python: Acceptable values are: "ID", "Output Category",
"Output Multi-Category", "Output Regression", "Continuous", "Categorical",
"Date", "IGNORE", "Validation Split", and "NLP", though they are not case
sensitive.

message from Python:

message from Python: The column index of this unexpected value is:

message from Python: 1

message from Python: The entire row that we received is:

message from Python: ['output category', ' continuous', ' continuous', '
continuous', ' continuous', ' continuous', ' continuous', ' continuous', '
continuous', ' continuous', ' continuous', ' continuous', ' continuous', '
continuous', ' continuous', ' continuous', ' continuous', ' continuous', '
continuous', ' continuous', ' continuous', ' continuous', ' continuous', '
continuous', ' continuous']

message from Python:

---

message from Python: This is an error that prevents the rest of the
prorgram from running. Please fix and run machineJS again.

message from Python:

message from Python:

message from Python:

message from Python:

heard an error!

{ [Error: ValueError: ' continuous' is not in list]

  traceback: 'Traceback (most recent call last):\n  File
"/Users/melvindunnjr/Downloads/machineJS/node_modules/data-formatter/mainPythonProcess.py",
line 43, in <module>\n    dataDescription, headerRow, trainingLength, X,
idColumn, outputColumn, idHeader, problemType, dataDescriptionRaw,
hasCustomValidationSplit, validationSplitColumn =
concat.inputFiles(trainingFile, testingFile)\n  File
"/Users/melvindunnjr/Downloads/machineJS/node_modules/data-formatter/helperFunctions/concat.py",
line 35, in inputFiles\n    hasID, testHeaderValidationLength,
hasCustomValidationSplit = validation.dataDescription( dataDescriptionRaw
)\n  File
"/Users/melvindunnjr/Downloads/machineJS/node_modules/data-formatter/helperFunctions/validation.py",
line 27, in dataDescription\n    allowableValues.index(name)\nValueError:
\' continuous\' is not in list\n',

  executable: 'python',

  options: null,

  script:
'/Users/melvindunnjr/Downloads/machineJS/node_modules/data-formatter/mainPythonProcess.py',

  args: [
'{"trainingData":"/Users/melvindunnjr/Downloads/numerai_datasets/train_machinejs.csv","testingData":"/Users/melvindunnjr/Downloads/numerai_datasets/numerai_tournament_data.csv","trainingPrettyName":"train_machinejs","testingPrettyName":"numerai_tournament_data","joinFileName":"","on":false,"allFeatureCombinations":false,"keepAllFeatures":false,"outputFolder":"/Users/melvindunnjr/Downloads/machineJS/pySetup/data-formatterResults","test":false,"verbose":1,"join":false}'
],

  exitCode: 1 }

Thanks,

Melvin

**Comment by ClimbsRocks** [comment]
It looks like there's a space right before the word continuous.

**Comment by MelvinDunn** [comment]
Works. Thanks for taking a look.

**Comment by ClimbsRocks** [comment]
Of course; thanks for filing the issue and reaching out!

**Comment by MelvinDunn** [comment]
Had one question while I was looking at the ol' machina:

-How does this machine determine the starting points for hyperparams?
-How does it determine the validation size? (Couldn't find it)

Sorry, I was interested, and while I know I could easily just look at the
code myself, I thought you would know off the top of your head.

I'm extremely interested in AutoML, and I think this machine is, well,
wonderful.

Thanks again,

Melvin

**Comment by ClimbsRocks** [comment]
Migrating the question to machineJS so we've got it documented over there: 
https://github.com/ClimbsRocks/machineJS/issues/174

**Comment by MelvinDunn** [comment]
Great! How do I change the error method (RMSE, Logloss, AUC)?

You also said it uses a random start for hyper parameters. Are you using a
random seed, or is it a random number each time?
